# currently running withh stretch, as there are problems with running freetype support with buster
# see: https://github.com/docker-library/php/issues/865
FROM php:7.2-apache-stretch
RUN apt-get update && \
    apt-get install -y \
    sudo \
    libzip-dev \
    libpng-dev \
    libicu-dev \
    libbz2-dev \
    libmagickwand-dev \
    libwebp-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libxpm-dev \
    libfreetype6-dev
RUN pecl install imagick apcu &&\
    docker-php-ext-enable imagick &&\
    docker-php-ext-enable apcu 
RUN docker-php-ext-configure gd \
    --with-gd \
    --with-webp-dir \
    --with-jpeg-dir \
    --with-png-dir \
    --with-zlib-dir \
    --with-xpm-dir \
    --with-freetype-dir &&\
    docker-php-ext-configure zip \
    --with-libzip
RUN docker-php-ext-install gd &&\
    docker-php-ext-install zip &&\
    docker-php-ext-install pdo_mysql &&\
    docker-php-ext-install intl &&\
    docker-php-ext-install bz2 &&\
    docker-php-ext-install opcache &&\
    docker-php-ext-install pcntl
COPY conf/*.ini /usr/local/etc/php/conf.d/
RUN a2enmod rewrite &&\
    a2enmod headers
RUN rm -rf /var/lib/apt/lists/*
